variables:
  REGISTRY: registry.appunite.com
  IMAGE_NAME: registry.appunite.com/appunite/absences-bot

before_script:
  - export LANG=en_US.UTF-8

stages:
  - test
  - build
  - deploy

tests:
  image: norionomura/swift:421
  stage: test
  script:
    - swift test
  tags:
    - k8s

docker:
  image: docker:latest
  stage: build
  script:
    - docker version
    - docker build -t "$IMAGE_NAME:${CI_COMMIT_SHA:0:8}" -f Dockerfile .
    - docker login -u admin -p $CI_BUILD_TOKEN $REGISTRY
    - docker push "$IMAGE_NAME:${CI_COMMIT_SHA:0:8}"
  tags:
    - privileged

deploy:
  stage: deploy
  image: lwolf/kubectl_deployer:latest
  environment:
    name: staging
  before_script:
    - apk add --no-cache curl
  script:
    - kubectl config use-context gitlab-deploy
    - kubectl set image deployment absences-production absences-production="$IMAGE_NAME:${CI_COMMIT_SHA:0:8}" --record
  dependencies: []
  tags:
    - k8s
  when: manual
