version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/absencebot_development
    ports:
      - '8080:8080'
